# Generated by Django 4.2.7 on 2025-07-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
                'db_table': 'pereval_coords',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=10, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=10, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=10, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=10, verbose_name='Весна')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
                'db_table': 'pereval_level',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fam', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('otc', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'pereval_users',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=255, verbose_name='Красивое название')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('other_titles', models.CharField(blank=True, max_length=255, verbose_name='Альтернативные названия')),
                ('connect', models.TextField(blank=True, verbose_name='Что соединяет')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('status', models.CharField(choices=[('new', 'Новая запись'), ('pending', 'Взято в работу модератором'), ('accepted', 'Модерация прошла успешно'), ('rejected', 'Модерация не прошла')], default='new', max_length=10, verbose_name='Статус модерации')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passes.coords', verbose_name='Координаты')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passes.level', verbose_name='Уровень сложности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
                'db_table': 'pereval_added',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('data', models.ImageField(upload_to='passes/', verbose_name='Изображение')),
                ('pass_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='passes.pass', verbose_name='Перевал')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'pereval_images',
            },
        ),
    ]
